name: Compatibility

on:
  push:
  pull_request:

jobs:
  composer:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['7.4', '8.5']
        guzzle: ['^6.3', '^7.0']

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - run: composer require --no-update "guzzlehttp/guzzle:${{ matrix.guzzle }}"
      - run: composer update --prefer-dist --no-interaction
      - run: find src -name '*.php' -print0 | xargs -0 -n1 php -l
